### ISSUE TITLE
Are The Offsets Up To Date?

### ISSUE THREAD

**Issue by ghost** [AnusReaper/ApexGaming.py#3]
Before Trying I just wanted to confirm if the offsets were up to date, are they?

Also how about using pymem for these cheats? I'm just suggesting tho I couldn't make one so yeah great job!

**Comment by reciate** [comment]
I'm assuming it's not up to date due to being 4 months old. Pymem or the user-mode Windows API in general would not be an option due to Apex's kernel anti-cheat.

**Comment by ghost** [comment]
Hmmm also @reciate do you have discord? I'm down to pay you to update the cheat! Not a lot but defintely something
If you're interested join my server as I'm not accepting friend requests atm https://discord.gg/chilling
