### ISSUE TITLE
it doesnt do anything

### ISSUE THREAD

**Issue by Isakuki** [AnusReaper/ApexGaming.py#4]
when i opened the file with python it opened a window and instantly closed it. When im in game i click insert and try other buttons nothing happens. is there something wrong that im doing?

**Comment by reciate** [comment]
This is a 2 year old project. It needs updating and wasn't meant to be working out of the box anyway.

https://www.unknowncheats.me/forum/apex-legends/399056-apex-glow-aimbot-python.html
